#!/bin/bash

# Fonction pour obtenir le nombre de fichiers
get_file_count() {
  echo $(ls -1 | wc -l)
}

# Nombre correct de fichiers
correct_count=$(get_file_count)

# Demande à l'utilisateur de deviner
echo "Devinez le nombre de fichiers dans le répertoire actuel :"
while true; do
  read guess
  if [[ ! "$guess" =~ ^[0-9]+$ ]]; then
    echo "Veuillez entrer un nombre valide."
  elif (( guess < correct_count )); then
    echo "Trop bas! Essayez encore."
  elif (( guess > correct_count )); then
    echo "Trop haut! Essayez encore."
  else
    echo "Félicitations! Vous avez deviné le bon nombre de fichiers!"
    break
  fi
done
